#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid,       sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armRight2,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port3,           armRight1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightFront,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port5,           rightBack,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           armLeft2,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port10,          intakeRight,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	int leftEncoder =0, rightEncoder=0, armLeftEncoder=0, armRightEncoder=0;

	while(true){
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];

		leftEncoder = nMotorEncoder[leftFront]*-1;
		rightEncoder = nMotorEncoder[rightFront];
		armLeftEncoder = nMotorEncoder[armLeft2];
		armRightEncoder = nMotorEncoder[armRight2]*-1;

		//Arm Control
		if(vexRT[Btn6U]){
			if(SensorValue[solenoid] == 1)
				SensorValue[solenoid] = 0;
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
		}else if(vexRT[Btn6D]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}
		if(vexRT[Btn5U]){
			motor[intakeLeft] = 127;
			motor[intakeRight] = 127;
		}else if(vexRT[Btn5D]){
			motor[intakeLeft] = -127;
			motor[intakeRight] = -127;
		}else{
			motor[intakeLeft] = 0;
			motor[intakeRight] = 0;
		}
		if(vexRT[Btn7R]){
			SensorValue[solenoid] = 1;
		}
		if(vexRT[Btn7D]){
			SensorValue[claw] = 0;
		}else{
			SensorValue[claw] = 1;
		}
	}
}
