#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl3,  solenoid,       sensorDigitalOut)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armLeftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  armRightEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armRight2,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port3,           armRight1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightFront,    tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port5,           rightBack,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           armLeft2,      tmotorVex393, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port10,          intakeRight,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		motor[port2] = 127;
		motor[port3] = 127;
		motor[port8] = 127;
		motor[port9] = 127;
	}
}
