#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           intake1,       tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armLeft1,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armLeft2,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           armRight1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           armRight2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          claw,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	int lift = 0;
	int encoderValue = 0;
	while(true){

		//Drive Control
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];

			//Arm Control
		if(vexRT[Btn6U]){
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
		}else if(vexRT[Btn6D]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}

		//Auto Arm Lift
		if(vexRT[Btn8U]){
			encoderValue = 1234;
			if(SensorValue[rightEncoder] < encoderValue){
				lift = 2;
			}else{
				lift = 1;
			}
		}else if(vexRT[Btn8D]){
			encoderValue = 1234;
			if(SensorValue[rightEncoder] < encoderValue){
				lift = 2;
			}else{
				lift = 1;
			}
		}else if(vexRT[Btn8L]){
			encoderValue = 1234;
			if(SensorValue[rightEncoder] < encoderValue){
				lift = 2;
			}else{
				lift = 1;
			}
		}else{
			motor[intake1] = 0;
		}
		if(lift == 1){
			if(encoderValue == 0){
				lift = 0;
			}
			if(SensorValue[rightEncoder] < encoderValue){
				motor[armLeft1] = 127;
				motor[armLeft2] = 127;
				motor[armRight1] = 127;
				motor[armRight2] = 127;
			}else{
				lift = 0;
			}
		}else if(lift == 2){
			if(encoderValue == 0){
				lift = 0;
			}
			if(SensorValue[rightEncoder] > encoderValue){
				motor[armLeft1] = -127;
				motor[armLeft2] = -127;
				motor[armRight1] = -127;
				motor[armRight2] = -127;
			}else{
				lift = 0;
			}
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}

		//Cude Intake
		if(vexRT[Btn5U]){
			motor[intake1] = 127;
		}else if(vexRT[Btn5D]){
			motor[intake1] = -127;
		}else{
			motor[intake1] = 0;
		}
		if(vexRT[Btn7L]){
			if(SensorValue[claw] == 0){
				SensorValue[claw] = 1;
			}else if(SensorValue[claw] == 0){
				SensorValue[claw] = 0;
			}
		}
	}
}
