//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		if(vexRT[Btn6U]){
			motor[port1] = 127;
			motor[port10] = 127;
		}else if(vexRT[Btn6D]){
			motor[port1] = -127;
			motor[port10] = 127;
		}else{
			motor[port1] = 0;
			motor[port10] = 0;
		}
	}
}
