#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           armRight1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armRight2,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           intake1,       tmotorVex393, openLoop)
#pragma config(Motor,  port6,           intake2,       tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armLeft2,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	bool reverse = false;
	int lift = 0;
	int encoderValue = 0;

	while(true){

		//Drive Control
		if(reverse){
			motor[rightFront] = -vexRT[Ch3];
			motor[rightBack] = -vexRT[Ch3];
			motor[leftFront] = -vexRT[Ch2];
			motor[leftBack] = -vexRT[Ch2];
		}else{
			motor[rightFront] = vexRT[Ch2];
			motor[rightBack] = vexRT[Ch2];
			motor[leftFront] = vexRT[Ch3];
			motor[leftBack] = vexRT[Ch3];
		}
		if(vexRT[Btn6U]){
			if(SensorValue[solenoid] == 0){
				SensorValue[solenoid] = 1;
			}
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
		}else if(vexRT[Btn6D]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}

		if(vexRT[Btn8D]){
			if(reverse == true){
				reverse = false;
			}else{
				reverse = true;
			}
		}

		if(vexRT[Btn7R]){
			SensorValue[solenoid] = 1;
		}

		//Arm Control
		if(vexRT[Btn6U]){
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
		}else if(vexRT[Btn6D]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}
		if(vexRT[Btn5U]){
			motor[intake1] = 127;
			motor[intake2] = 127;
		}else if(vexRT[Btn5D]){
			motor[intake1] = -127;
			motor[intake2] = -127;
		}else{
			motor[intake1] = 0;
			motor[intake2] = 0;
		}

	}
}
