#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  intakeEncoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl11, leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           armRight1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armRight2,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           intake1,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           intake2,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armLeft2,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

int whichCode = 0;
string programNames[4] = {"left", "right", "front", "back"};

void pre_auton(){
	//be honest, you dont know what this does, dont touch it, keep it true
	bStopTasksBetweenModes = true;

	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDCenteredString(0, "dfsdfsdfsd");
	displayLCDCenteredString(1, "<    Enter!    >");
	while(nLCDButtons != 2){
		displayLCDCenteredString(0, programNames[whichCode]);
		displayLCDCenteredString(1, "<    Enter!    >");
		while(nLCDButtons == 0){
			wait1Msec(5);
		}
		if(nLCDButtons == 1){
			while(nLCDButtons != 0){
				wait1Msec(10);
			}
			whichCode--;
			if(whichCode < 0){
				whichCode = 3;
			}
			}else if(nLCDButtons == 4){
			while(nLCDButtons != 0){
				wait1Msec(10);
			}
			whichCode++;
			if(whichCode >= 4){
				whichCode = 0;
			}
		}
	}
	StartTask(autonomous);
}

task autonomous(){
	while(true){
			motor[rightBack] = -127;
			motor[leftBack] = -127;
			motor[rightFront] = -127;
			motor[leftFront] = -127;
		}
	/*switch(whichCode){
	case 0:
		while(SensorValue[rightEncoder] < 300){
			motor[rightBack] = 100;
			motor[rightFront] = 100;
		}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
		break;
	case 1:
		while(SensorValue[leftEncoder] < 300){
			motor[leftBack] = 100;
			motor[leftFront] = 100;
		}
		motor[leftBack] = 0;
		motor[leftFront] = 0;
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
		break;
	case 2:
		while(SensorValue[rightEncoder] < 300000){
			motor[rightBack] = 127;
			motor[rightFront] = 127;
			motor[leftBack] = 127;
			motor[leftFront] = 127;
		}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
		motor[leftBack] = 0;
		motor[leftFront] = 0;
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
		break;
	case 3:
		while(SensorValue[rightEncoder] > -300000){
			motor[rightBack] = -127;
			motor[leftBack] = -127;
			motor[rightFront] = -127;
			motor[leftFront] = -127;
		}
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
		break;
	}*/
}

task usercontrol(){
	int lift = 0;
	int encoderValue = 0;
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;

	while(true){
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];

		//Arm Control
		if(vexRT[Btn6UXmtr2]){
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
			}else if(vexRT[Btn6DXmtr2]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
			}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}
		if(vexRT[Btn5UXmtr2]){
			motor[intake1] = 127;
			motor[intake2] = 127;
			}else if(vexRT[Btn5DXmtr2]){
			motor[intake1] = -127;
			motor[intake2] = -127;
			}else{
			motor[intake1] = 0;
			motor[intake2] = 0;
		}
	}
}
