#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  claw,           sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armRight2,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port3,           armRight1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightFront,    tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port5,           rightBack,     tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           leftBack,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           leftFront,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           armLeft2,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port10,          intakeRight,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftEncoder =0, rightEncoder=0, armLeftEncoder=0, armRightEncoder=0;
int speed = 80, armSpeed = 80;
int open = 1, close = 0;

void updateEncoders(){
		leftEncoder = nMotorEncoder[leftFront];
		rightEncoder = nMotorEncoder[rightFront]*-1;
		armLeftEncoder = nMotorEncoder[armLeft2]*-1;
		if(armLeftEncoder < 0){
			nMotorEncoder[armLeft2] = 0;
			armLeftEncoder = 0;
		}
		armRightEncoder = nMotorEncoder[armRight2];
		if(armRightEncoder < 0){
			nMotorEncoder[armRight2] = 0;
			armRightEncoder = 0;
		}
}

void backRight(int value){
	updateEncoders();
	int startV = rightEncoder;
	while(rightEncoder > -value){
		motor[rightBack] = -speed;
		motor[rightFront] = -speed;
		updateEncoders();
	}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
}

void backLeft(int value){
	updateEncoders();
	int startV = leftEncoder;
	while(leftEncoder > startV-value){//1
		motor[leftBack] = -speed;
		motor[leftFront] = -speed;
		updateEncoders();
	}
		motor[leftBack] = 0;
		motor[leftFront] = 0;
}

void right(int value){
	updateEncoders();
	int startV = leftEncoder;
	while(leftEncoder < startV + value){
		motor[leftBack] = speed;
		motor[leftFront] = speed;
		updateEncoders();
	}
	motor[leftBack] = 0;
	motor[leftFront] = 0;
}

void left(int value){
	updateEncoders();
	int startV = rightEncoder;
	while(rightEncoder < startV + value){
		motor[rightBack] = speed*.6;
		motor[rightFront] = speed*.6;
		updateEncoders();
	}
	motor[rightBack] = 0;
	motor[rightFront] = 0;
}

void armUp(int value){
	while(armLeftEncoder < value){
		motor[armLeft1] = armSpeed;
		motor[armLeft2] = armSpeed;
		motor[armRight1] = armSpeed;
		motor[armRight2] = armSpeed;
		updateEncoders();
	}
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
		updateEncoders();
}

void armDown(int value){
	while(armRightEncoder > value){
		motor[armLeft1] = -armSpeed;
		motor[armLeft2] = -armSpeed;
		motor[armRight1] = -armSpeed;
		motor[armRight2] = -armSpeed;
		updateEncoders();
	}
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
		updateEncoders();
}

void flipOut(){
		motor[armLeft1] = 127;
		motor[armLeft2] = 127;
		motor[armRight1] = 127;
		motor[armRight2] = 127;
		wait1Msec(250);
		motor[armLeft1] = -127;
		motor[armLeft2] = -127;
		motor[armRight1] = -127;
		motor[armRight2] = -127;
		wait1Msec(250);
		SensorValue[claw] = open;
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
		nMotorEncoder[armLeft2] = 0;
		nMotorEncoder[armRight2] = 0;
}

void intake(){
	motor[armLeft1] = -127;
	motor[armLeft2] = -127;
	motor[armRight1] = -127;
	motor[armRight2] = -127;
	wait1Msec(200);//wait .02 sec (every time I do this in future is because this small thing stops bot from carrying its previous momentum forward)
	SensorValue[claw] = close;//close claw
	wait1Msec(100);
	motor[armLeft1] = 0;
	motor[armLeft2] = 0;
	motor[armRight1] = 0;
	motor[armRight2] = 0;
}

task main(){
	//flipOut();
	nMotorEncoder[armLeft2] = 0;
	nMotorEncoder[armRight2] = 0;
	SensorValue[claw] = open;//close claw
	wait1Msec(1000);//wait
	intake();
	//armUp(250);//arm up just enough
	wait1Msec(20);//wait
	backRight(265);//first turn towards goal
	/*right(185);//second turn towards goal
	wait1Msec(500);//wait
	armDown(0);
	SensorValue[claw] = 0;//open claw
	wait1Msec(500);//wait
	/*armUp(150);
	wait1Msec(20);//wait
	backLeft(200);//turn 1
	armDown(160);
	wait1Msec(50);//wait
	left(275);//turn     2



	wait1Msec(1000);//wait
	SensorValue[claw] = 1;//close claw
	wait1Msec(20);//wait .02 sec (every time I do this in future is because this small thing stops bot from carrying its previous momentum forward)
	armUp(200);//arm up just enough
	wait1Msec(20);//wait
	backRight(225);//first turn towards goal
	right(235);//second turn towards goal
	wait1Msec(500);//wait
	armDown(0);
	SensorValue[claw] = 0;//open claw
	wait1Msec(500);//wait
	armUp(150);
	wait1Msec(20);//wait
	backLeft(200);//turn 1
	armDown(160);
	wait1Msec(50);//wait
	left(325);//turn     2

	///REPEAT EVERYTHING

	/*wait1Msec(750);//wait
	SensorValue[claw] = 1;//close claw
	wait1Msec(20);//wait .02 sec (every time I do this in future is because this small thing stops bot from carrying its previous momentum forward)
	armUp(250);//arm up just enough
	wait1Msec(20);//wait
	//backRight(250);//first turn towards goal
	//right(225);//second turn towards goal
	backRight(275);//first turn towards goal
	right(175);//second turn towards goal
	wait1Msec(250);//wait
	armDown(250);
	SensorValue[claw] = 0;//open claw
	wait1Msec(500);//wait
	armUp(150);
	wait1Msec(20);//wait
	backLeft(225);
	armDown(150);
	wait1Msec(50);//wait
	left(300);

	///REPEAT EVERYTHING
	wait1Msec(750);//wait*/
}
