#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  armSolenoid,    sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armRight2,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port3,           armRight1,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightFront,    tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port5,           rightBack,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           leftBack,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftFront,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port8,           armLeft1,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           armLeft2,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port10,          intakeRight,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int leftEncoder =0, rightEncoder=0, armLeftEncoder=0, armRightEncoder=0;
int speed = 80, armSpeed = 60;

void updateEncoders(){
		leftEncoder = nMotorEncoder[leftFront];
		rightEncoder = nMotorEncoder[rightFront]*-1;
		armLeftEncoder = nMotorEncoder[armLeft2]*-1;
		if(armLeftEncoder < 0){
			nMotorEncoder[armLeft2] = 0;
			armLeftEncoder = 0;
		}
		armRightEncoder = nMotorEncoder[armRight2]*-1;
		if(armRightEncoder < 0){
			nMotorEncoder[armRight2] = 0;
			armRightEncoder = 0;
		}
}

void backRight(int value){
	updateEncoders();
	int startV = rightEncoder;
	while(rightEncoder > startV-value){//1
		motor[rightBack] = -speed;
		motor[rightFront] = -speed;
		updateEncoders();
	}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
}

void backLeft(int value){
	updateEncoders();
	int startV = leftEncoder;
	while(leftEncoder > startV-value){//1
		motor[leftBack] = -speed;
		motor[leftFront] = -speed;
		updateEncoders();
	}
		motor[leftBack] = 0;
		motor[leftFront] = 0;
}

void right(int value){
	updateEncoders();
	int startV = leftEncoder;
	while(leftEncoder < startV + value){
		motor[leftBack] = speed;
		motor[leftFront] = speed;
		updateEncoders();
	}
	motor[leftBack] = 0;
	motor[leftFront] = 0;
}

void left(int value){
	updateEncoders();
	int startV = rightEncoder;
	while(rightEncoder < startV + value){
		motor[rightBack] = speed*.6;
		motor[rightFront] = speed*.6;
		updateEncoders();
	}
	motor[rightBack] = 0;
	motor[rightFront] = 0;
}

void armUp(int value){
	while(armRightEncoder < value){
		motor[armLeft1] = armSpeed;
		motor[armLeft2] = armSpeed;
		motor[armRight1] = armSpeed;
		motor[armRight2] = armSpeed;
		updateEncoders();
	}
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
		updateEncoders();
}

void armDown(int value){
	while(armRightEncoder > value){
		motor[armLeft1] = -armSpeed;
		motor[armLeft2] = -armSpeed;
		motor[armRight1] = -armSpeed;
		motor[armRight2] = -armSpeed;
		updateEncoders();
	}
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
		updateEncoders();
}

void pre_auton(){
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
  nMotorEncoder[leftFront] = 0;
  nMotorEncoder[rightFront] = 0;
  nMotorEncoder[armLeft2] = 0;
  nMotorEncoder[armRight2] = 0;
  SensorValue[armSolenoid] = 0;
  SensorValue[claw] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous(){
	wait1Msec(1000);//wait
	SensorValue[claw] = 1;//close claw
	wait1Msec(20);//wait .02 sec (every time I do this in future is because this small thing stops bot from carrying its previous momentum forward)
	armUp(100);//arm up just enough
	wait1Msec(20);//wait
	backRight(265);//first turn towards goal
	right(185);//second turn towards goal
	wait1Msec(500);//wait
	armDown(0);
	SensorValue[claw] = 0;//open claw
	wait1Msec(500);//wait
	armUp(150);
	wait1Msec(20);//wait
	backLeft(200);//turn 1
	armDown(160);
	wait1Msec(50);//wait
	left(275);//turn     2

	wait1Msec(1000);//wait
	SensorValue[claw] = 1;//close claw
	wait1Msec(20);//wait .02 sec (every time I do this in future is because this small thing stops bot from carrying its previous momentum forward)
	armUp(200);//arm up just enough
	wait1Msec(20);//wait
	backRight(225);//first turn towards goal
	right(235);//second turn towards goal
	wait1Msec(500);//wait
	armDown(0);
	SensorValue[claw] = 0;//open claw
	wait1Msec(500);//wait
	armUp(150);
	wait1Msec(20);//wait
	backLeft(200);//turn 1
	armDown(160);
	wait1Msec(50);//wait
	left(325);//turn     2
}

task usercontrol(){
	int leftEncoder =0, rightEncoder=0, armLeftEncoder=0, armRightEncoder=0;

	while(true){
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];

		//Arm Control
		if(vexRT[Btn6UXmtr2]){
			if(SensorValue[armSolenoid] == 1)
				SensorValue[armSolenoid] = 0;
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
		}else if(vexRT[Btn6DXmtr2]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}
		if(vexRT[Btn5UXmtr2]){
			motor[intakeLeft] = 127;
			motor[intakeRight] = 127;
		}else if(vexRT[Btn5DXmtr2]){
			motor[intakeLeft] = -127;
			motor[intakeRight] = -127;
		}else{
			motor[intakeLeft] = 0;
			motor[intakeRight] = 0;
		}
		if(vexRT[Btn7RXmtr2]){
			SensorValue[armSolenoid] = 1;
		}
		if(vexRT[Btn7DXmtr2]){
			SensorValue[claw] = 0;
		}else{
			SensorValue[claw] = 1;
		}
	}
}
