#pragma config(Sensor, dgtl1,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  armSolenoid,    sensorDigitalOut)
#pragma config(Sensor, dgtl3,  intakeSolenoid, sensorDigitalOut)
#pragma config(Sensor, dgtl4,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  armLeftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl10, armRightEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           leftFront,     tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port2,           leftMiddle,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           armLeft2,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           armLeft1,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           armRight1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armRight2,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightBack,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           rightMiddle,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          rightFront,    tmotorVex393HighSpeed, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int speed = 80, armSpeed = 80;
int open = 1, close = 0;

void forward(int value){
	while(SensorValue[rightEncoder]  < value){
		motor[rightBack] = speed;
		motor[rightMiddle] = speed;
		motor[rightFront] = speed;
		motor[leftBack] = speed;
		motor[leftMiddle] = speed;
		motor[leftFront] = speed;
	}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
		motor[rightMiddle] = 0;
		motor[leftBack] = 0;
		motor[leftMiddle] = 0;
		motor[leftFront] = 0;
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
}

void forwardSpeed(int value, int speed){
	while(SensorValue[rightEncoder] < value){
		motor[rightBack] = speed;
		motor[rightMiddle] = speed;
		motor[rightFront] = speed;
		motor[leftBack] = speed;
		motor[leftMiddle] = speed;
		motor[leftFront] = speed;
	}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
		motor[rightMiddle] = 0;
		motor[leftBack] = 0;
		motor[leftMiddle] = 0;
		motor[leftFront] = 0;
		SensorValue[rightEncoder] = 0;
		SensorValue[SensorValue[leftEncoder] ] = 0;
}
void backward(int value){
	while(SensorValue[rightEncoder] > -value){
		motor[rightBack] = -speed;
		motor[rightMiddle] = -speed;
		motor[rightFront] = -speed;
		motor[leftBack] = -speed;
		motor[leftMiddle] = -speed;
		motor[leftFront] = -speed;
	}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
		motor[rightMiddle] = 0;
		motor[leftBack] = 0;
		motor[leftMiddle] = 0;
		motor[leftFront] = 0;
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
}

void backRight(int value){
	int startV = rightEncoder;
	while(SensorValue[rightEncoder] > -value){
		motor[rightBack] = -speed;
		motor[rightMiddle] = -speed;
		motor[rightFront] = -speed;
	}
		motor[rightBack] = 0;
		motor[rightFront] = 0;
}

void backLeft(int value){
	int startV = leftEncoder;
	while(SensorValue[leftEncoder] > startV-value){//1
		motor[leftBack] = -speed;
		motor[leftMiddle] = -speed;
		motor[leftFront] = -speed;
	}
		motor[leftBack] = 0;
		motor[leftMiddle] = 0;
		motor[leftFront] = 0;
}

void right(int value){
	int startV = leftEncoder;
	while(SensorValue[leftEncoder] < startV + value){
		motor[leftBack] = speed;
		motor[leftMiddle] = speed;
		motor[leftFront] = speed;
	}
	motor[leftBack] = 0;
	motor[leftMiddle] = 0;
	motor[leftFront] = 0;
}

void left(int value){
	int startV = rightEncoder;
	while(SensorValue[rightEncoder] < startV + value){
		motor[rightBack] = speed;
		motor[rightMiddle] = speed;
		motor[rightFront] = speed;
	}
	motor[rightBack] = 0;
	motor[rightMiddle] = 0;
	motor[rightFront] = 0;
}

void armUp(int value){
	while(SensorValue[armLeftEncoder]  < value){
		motor[armLeft1] = armSpeed;
		motor[armLeft2] = armSpeed;
		motor[armRight1] = armSpeed;
		motor[armRight2] = armSpeed;
	}
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
}

void armDown(int value){
	while(SensorValue[armLeftEncoder] > value){
		motor[armLeft1] = -armSpeed;
		motor[armLeft2] = -armSpeed;
		motor[armRight1] = -armSpeed;
		motor[armRight2] = -armSpeed;
	}
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
}

void flipOut(){
		motor[armLeft1] = 127;
		motor[armLeft2] = 127;
		motor[armRight1] = 127;
		motor[armRight2] = 127;
		wait1Msec(250);
		motor[armLeft1] = -127;
		motor[armLeft2] = -127;
		motor[armRight1] = -127;
		motor[armRight2] = -127;
		wait1Msec(250);
		SensorValue[claw] = open;
		motor[armLeft1] = 0;
		motor[armLeft2] = 0;
		motor[armRight1] = 0;
		motor[armRight2] = 0;
		nMotorEncoder[armLeft2] = 0;
		nMotorEncoder[armRight2] = 0;
}

void intake(){
	/*motor[armLeft1] = -127;
	motor[armLeft2] = -127;
	motor[armRight1] = -127;
	motor[armRight2] = -127;
	wait1Msec(200);//wait .02 sec (future: because this small thing stops bot from carrying its previous momentum forward)
	SensorValue[claw] = close;//close claw
	wait1Msec(100);
	motor[armLeft1] = 0;
	motor[armLeft2] = 0;
	motor[armRight1] = 0;
	motor[armRight2] = 0;*/
	SensorValue[claw] = close;//close claw
}

void pre_auton(){
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
  nMotorEncoder[leftFront] = 0;
  nMotorEncoder[rightFront] = 0;
  nMotorEncoder[armLeft2] = 0;
  nMotorEncoder[armRight2] = 0;
  SensorValue[claw] = 0;
  SensorValue[armSolenoid] = 0;
  SensorValue[intakeSolenoid] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous(){
		motor[leftBack] = 127;
		motor[leftMiddle] = 127;
		motor[rightBack] = 127;
		motor[leftFront] = 127;
		motor[rightMiddle] = 127;
		motor[rightFront] = 127;
		wait1Msec(1500);
	motor[leftBack] = 0;
	motor[rightBack] = 0;
	motor[leftFront] = 0;
	motor[rightFront] = 0;
	motor[leftMiddle] = 0;
	motor[rightMiddle] = 127;
}

task usercontrol(){
	bool backwardControl;
	bool slow;
	while(true){
		float leftCh = vexRT[Ch3];
		float rightCh = vexRT[Ch2];
		if(slow){
			leftCh *= 0.6;
			rightCh *= 0.6;
		}
		if(backwardControl){
			motor[rightFront] = rightCh;
			motor[rightMiddle] = rightCh;
			motor[rightBack] = rightCh;
			motor[leftFront] = leftCh;
			motor[leftMiddle] = leftCh;
			motor[leftBack] = leftCh;
		}else{
			motor[rightFront] = -rightCh;
			motor[rightMiddle] = -rightCh;
			motor[rightBack] = -rightCh;
			motor[leftFront] = -leftCh;
			motor[leftMiddle] = -leftCh;
			motor[leftBack] = -leftCh;
		}

		//Arm Control
		if(vexRT[Btn6UXmtr2]){
			if(SensorValue[armSolenoid] == 1)
				SensorValue[armSolenoid] = 0;
			motor[armLeft1] = 127;
			motor[armLeft2] = 127;
			motor[armRight1] = 127;
			motor[armRight2] = 127;
		}else if(vexRT[Btn6DXmtr2]){
			motor[armLeft1] = -127;
			motor[armLeft2] = -127;
			motor[armRight1] = -127;
			motor[armRight2] = -127;
		}else{
			motor[armLeft1] = 0;
			motor[armLeft2] = 0;
			motor[armRight1] = 0;
			motor[armRight2] = 0;
		}
		if(vexRT[Btn7RXmtr2]){
			SensorValue[armSolenoid] = 1;
		}
		if(vexRT[Btn7DXmtr2]){
			if(SensorValue[claw] == 0){
				SensorValue[claw] = 1;
				wait1Msec(100);
			}else{
				SensorValue[claw] = 0;
				wait1Msec(100);
			}
		}
		if(vexRT[Btn6U]){
			if(backwardControl == true){
				backwardControl = false;
				wait1Msec(100);
			}else{
				backwardControl = true;
				wait1Msec(100);
			}
		}
		if(vexRT[Btn6D]){
			if(slow == true){
				slow = false;
			}else{
				slow = true;
			}
		}
    if(vexRT[Btn7LXmtr2]){
			SensorValue[intakeSolenoid] = 0;
				wait1Msec(100);
		}else{
			SensorValue[intakeSolenoid] = 1;
				wait1Msec(100);
		}
	}
}
